--- ts-1.0/Makefile.orig	2016-10-20 05:12:15.000000000 +0900
+++ ts-1.0/Makefile	2019-03-27 05:21:44.505798264 +0900
@@ -55,7 +55,7 @@
 	rm -f *.o ts
 
 install: ts
-	$(INSTALL) -d $(PREFIX)/bin
-	$(INSTALL) ts $(PREFIX)/bin
-	$(INSTALL) -d $(PREFIX)/share/man/man1
-	$(INSTALL) -m 644 ts.1 $(PREFIX)/share/man/man1
+	$(INSTALL) -d $(DESTDIR)/$(PREFIX)/bin
+	$(INSTALL) ts $(DESTDIR)/$(PREFIX)/bin
+	$(INSTALL) -d $(DESTDIR)/$(PREFIX)/share/man/man1
+	$(INSTALL) -m 644 ts.1 $(DESTDIR)/$(PREFIX)/share/man/man1
