*** unrar/makefile.orig	2022-03-19 18:13:32.924467976 +0900
--- unrar/makefile	2022-03-19 18:16:27.301477188 +0900
***************
*** 161,174 ****
  	$(AR) rcs libunrar.a $(OBJECTS) $(LIB_OBJ)
  
  install-unrar:
! 			install -D unrar $(DESTDIR)/bin/unrar
  
  uninstall-unrar:
! 			rm -f $(DESTDIR)/bin/unrar
  
  install-lib:
! 		install libunrar.so $(DESTDIR)/lib
! 		install libunrar.a $(DESTDIR)/lib
  
  uninstall-lib:
! 		rm -f $(DESTDIR)/lib/libunrar.so
--- 161,174 ----
  	$(AR) rcs libunrar.a $(OBJECTS) $(LIB_OBJ)
  
  install-unrar:
! 			install -D unrar $(DESTDIR)/usr/bin/unrar
  
  uninstall-unrar:
! 			rm -f $(DESTDIR)/usr/bin/unrar
  
  install-lib:
! 		install libunrar.so $(DESTDIR)/usr/$(libdir)
! 		install libunrar.a $(DESTDIR)/usr/$(libdir)
  
  uninstall-lib:
! 		rm -f $(DESTDIR)/usr/$(libdir)/libunrar.so
